application: monitorizepyy
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /js
  static_dir: static/js


- url: /css
  static_dir: static/css

- url: /icons
  static_dir: static/icons

- url: /img
  static_dir: static/img

- url: /signup
  script: main.app

- url: /login
  script: main.app

- url: /forgot
  script: main.app

- url: .*
  script: main.app


libraries:
- name: webapp2
  version: "2.5.1"
